title: Lin Yujian's Homepage
page-top-title: Lin Yujian
top-section-bg-text: Intelligent Science and Technology
home-subtitle: Lin Yujian&ensp;|&ensp;林煜剑
copyright-text: '&copy; Yujian Lin 2025-2026. All Rights Reserved.'
